# -*- coding: utf-8 -*-
"""Project (3) Web_scraping_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oV3KNspVRHZM9KUZPa1DgVqbI9QiL2a3
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd

def scrap():
  titles_all = []
  links_all = []
  occupations_all = []
  companies_all = []
  specs_all = []

  response = requests.get('https://wuzzuf.net/search/jobs/?a=hpb&q=machine%20learning&start=0')
  soup = BeautifulSoup(response.content, 'lxml')
  pages = soup.find_all("button", {'class': 'css-1dtj1k4 ezfki8j0'})
  pages_lst = [int(page.text) for page in pages]
  
  for i in range(pages_lst[-1]):
    response = requests.get('https://wuzzuf.net/search/jobs/?a=hpb&q=machine%20learning&start='+str(i))
    soup = BeautifulSoup(response.content, 'lxml')

    titles = soup.find_all("h2", {'class': 'css-m604qf'})
    titles_lst = [title.a.text for title in titles]
    titles_all = titles_all + titles_lst

    links = ['https://wuzzuf.net' + title.a['href'] for title in titles]
    links_all = links_all + links

    occupations = soup.find_all("div", {'class': 'css-1lh32fc'})
    occupations_lst = [occupation.text for occupation in occupations]
    occupations_all = occupations_all + occupations_lst

    companies = soup.find_all("a", {'class': 'css-17s97q8'})
    companies_lst = [company.text for company in companies]
    companies_all = companies_all + companies_lst

    specs = soup.find_all("div", {'class': 'css-y4udm8'})
    specs_lst = [spec.text for spec in specs]
    specs_all = specs_all + specs_lst

    scraped_data = {}
    scraped_data['Title'] = titles_all
    scraped_data['Link'] = links_all
    scraped_data['Occupation'] = occupations_all
    scraped_data['Company'] = companies_all
    scraped_data['Specs'] = specs_all

  df = pd.DataFrame(scraped_data)
  df.to_csv('mljobs.csv', index=False)
  print("Jobs Scraped Successfully")
  return df

if __name__ == '__main__':
    scrap()

scrap()