# -*- coding: utf-8 -*-
"""titles_scraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g_aTOVJCEtXCr_XSlLzpvbgIr05BawEu
"""

import jobs_scraping

def tiltles():
  df = jobs_scraping.scrap()
  titles = df['Title'].tolist()
  return titles


if __name__ == '__main__':
  print(titles())